/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ➡️HeliDrone Surveys⬅️ (https://sketchfab.com/HeliDroneSurveys)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/drone-animv1-af9e397e25b542bfaff8db7c8291e367
Title: Drone_AnimV1
*/

import * as THREE from "three";
import { useEffect, type JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useSimulationStore } from "@/hooks/use-simulation-store";
import { Status as AnimationStatus } from "./viewport-animation-controls";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_32: THREE.SkinnedMesh;
    Object_33: THREE.SkinnedMesh;
    Object_34: THREE.SkinnedMesh;
    Object_35: THREE.SkinnedMesh;
    Object_36: THREE.SkinnedMesh;
    Object_37: THREE.SkinnedMesh;
    Object_38: THREE.SkinnedMesh;
    Object_39: THREE.SkinnedMesh;
    Object_41: THREE.SkinnedMesh;
    Object_42: THREE.SkinnedMesh;
    Object_43: THREE.SkinnedMesh;
    Object_44: THREE.SkinnedMesh;
    Object_45: THREE.SkinnedMesh;
    Object_46: THREE.SkinnedMesh;
    Object_47: THREE.SkinnedMesh;
    Object_48: THREE.SkinnedMesh;
    Object_49: THREE.SkinnedMesh;
    Object_51: THREE.SkinnedMesh;
    Object_52: THREE.SkinnedMesh;
    Object_53: THREE.SkinnedMesh;
    Object_54: THREE.SkinnedMesh;
    Object_56: THREE.SkinnedMesh;
    Object_58: THREE.SkinnedMesh;
    Object_59: THREE.SkinnedMesh;
    Object_60: THREE.SkinnedMesh;
    Object_61: THREE.SkinnedMesh;
    Object_63: THREE.SkinnedMesh;
    Object_64: THREE.SkinnedMesh;
    Object_65: THREE.SkinnedMesh;
    Object_66: THREE.SkinnedMesh;
    Object_67: THREE.SkinnedMesh;
    Object_68: THREE.SkinnedMesh;
    Object_69: THREE.SkinnedMesh;
    Object_70: THREE.SkinnedMesh;
    Object_71: THREE.SkinnedMesh;
    Object_72: THREE.SkinnedMesh;
    Object_73: THREE.SkinnedMesh;
    Object_74: THREE.SkinnedMesh;
    Object_76: THREE.SkinnedMesh;
    Object_77: THREE.SkinnedMesh;
    Object_78: THREE.SkinnedMesh;
    Object_79: THREE.SkinnedMesh;
    Object_81: THREE.SkinnedMesh;
    Object_82: THREE.SkinnedMesh;
    Object_83: THREE.SkinnedMesh;
    Object_84: THREE.SkinnedMesh;
    Object_85: THREE.SkinnedMesh;
    Object_86: THREE.SkinnedMesh;
    Object_87: THREE.SkinnedMesh;
    Object_88: THREE.SkinnedMesh;
    Object_90: THREE.SkinnedMesh;
    Object_91: THREE.SkinnedMesh;
    Object_92: THREE.SkinnedMesh;
    Object_93: THREE.SkinnedMesh;
    Object_95: THREE.SkinnedMesh;
    Object_96: THREE.SkinnedMesh;
    Object_97: THREE.SkinnedMesh;
    Object_98: THREE.SkinnedMesh;
    Object_99: THREE.SkinnedMesh;
    Object_100: THREE.SkinnedMesh;
    Object_101: THREE.SkinnedMesh;
    Object_102: THREE.SkinnedMesh;
    Object_103: THREE.SkinnedMesh;
    Object_105: THREE.SkinnedMesh;
    Object_106: THREE.SkinnedMesh;
    Object_107: THREE.SkinnedMesh;
    Object_108: THREE.SkinnedMesh;
    Object_109: THREE.SkinnedMesh;
    Object_110: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    Glass_Object_Solid_Simple_black: THREE.MeshStandardMaterial;
    PMMA_Opaque_Olive: THREE.MeshStandardMaterial;
    Special_Finish_Weathered_Black_Steel: THREE.MeshStandardMaterial;
    PVC_Fb_Black: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    Clean_Aluminium_Matte: THREE.MeshStandardMaterial;
    Clean_Iron_scrow: THREE.MeshStandardMaterial;
    METALSmoothChrome_Satin: THREE.MeshStandardMaterial;
    METALSmoothAluminium: THREE.MeshStandardMaterial;
    Material_45: THREE.MeshStandardMaterial;
    Clean_Iron_Mash: THREE.MeshStandardMaterial;
    standardSurface1: THREE.MeshStandardMaterial;
    Inside_camera_Black: THREE.MeshStandardMaterial;
    GLASSDecorativeRainbow_Reflection: THREE.MeshStandardMaterial;
    Glass_Object_Solid_Simple: THREE.MeshStandardMaterial;
    blue_crim: THREE.MeshStandardMaterial;
    Inside_out_camera_Black: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "Deformation_JNT|Deformation_JNT|Take 001|BaseLayer";

type DroneModelProps = JSX.IntrinsicElements["group"] & {
  ref: React.RefObject<THREE.Group>;
};

const DroneModel: React.FC<DroneModelProps> = ({ ref, ...props }) => {
  const { nodes, materials, animations } = useGLTF(
    "/drone_animv1.glb",
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, ref);
  const animationStatus = useSimulationStore.use.animationStatus();

  useEffect(() => {
    const action =
      actions["Deformation_JNT|Deformation_JNT|Take 001|BaseLayer"];
    if (!action) return;

    if (animationStatus === AnimationStatus.Playing) {
      action.paused = false;
      action.timeScale = 0.8;
      action.play();
    }

    if (animationStatus === AnimationStatus.Paused) {
      action.paused = true;
    }

    if (animationStatus === AnimationStatus.Ended) {
      action.stop();
    }

    return () => {
      action.stop();
    };
  }, [actions, animationStatus]);

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group
            name="e68253844ffe47dfab64fdfb918b786dfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
            userData={{ name: "e68253844ffe47dfab64fdfb918b786d.fbx" }}
          >
            <group name="Object_2" userData={{ name: "Object_2" }}>
              <group name="RootNode" userData={{ name: "RootNode" }}>
                <group
                  name="Deformation_JNT"
                  userData={{ name: "Deformation_JNT" }}
                >
                  <group name="Object_5" userData={{ name: "Object_5" }}>
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_32"
                      geometry={nodes.Object_32.geometry}
                      material={materials.Glass_Object_Solid_Simple_black}
                      skeleton={nodes.Object_32.skeleton}
                      userData={{ name: "Object_32" }}
                    />
                    <skinnedMesh
                      name="Object_33"
                      geometry={nodes.Object_33.geometry}
                      material={materials.PMMA_Opaque_Olive}
                      skeleton={nodes.Object_33.skeleton}
                      userData={{ name: "Object_33" }}
                    />
                    <skinnedMesh
                      name="Object_34"
                      geometry={nodes.Object_34.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_34.skeleton}
                      userData={{ name: "Object_34" }}
                    />
                    <skinnedMesh
                      name="Object_35"
                      geometry={nodes.Object_35.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_35.skeleton}
                      userData={{ name: "Object_35" }}
                    />
                    <skinnedMesh
                      name="Object_36"
                      geometry={nodes.Object_36.geometry}
                      material={materials.blue}
                      skeleton={nodes.Object_36.skeleton}
                      userData={{ name: "Object_36" }}
                    />
                    <skinnedMesh
                      name="Object_37"
                      geometry={nodes.Object_37.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_37.skeleton}
                      userData={{ name: "Object_37" }}
                    />
                    <skinnedMesh
                      name="Object_38"
                      geometry={nodes.Object_38.geometry}
                      material={materials.Clean_Iron_scrow}
                      skeleton={nodes.Object_38.skeleton}
                      userData={{ name: "Object_38" }}
                    />
                    <skinnedMesh
                      name="Object_39"
                      geometry={nodes.Object_39.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_39.skeleton}
                      userData={{ name: "Object_39" }}
                    />
                    <skinnedMesh
                      name="Object_41"
                      geometry={nodes.Object_41.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_41.skeleton}
                      userData={{ name: "Object_41" }}
                    />
                    <skinnedMesh
                      name="Object_42"
                      geometry={nodes.Object_42.geometry}
                      material={materials.Clean_Iron_scrow}
                      skeleton={nodes.Object_42.skeleton}
                      userData={{ name: "Object_42" }}
                    />
                    <skinnedMesh
                      name="Object_43"
                      geometry={nodes.Object_43.geometry}
                      material={materials.Glass_Object_Solid_Simple_black}
                      skeleton={nodes.Object_43.skeleton}
                      userData={{ name: "Object_43" }}
                    />
                    <skinnedMesh
                      name="Object_44"
                      geometry={nodes.Object_44.geometry}
                      material={materials.PMMA_Opaque_Olive}
                      skeleton={nodes.Object_44.skeleton}
                      userData={{ name: "Object_44" }}
                    />
                    <skinnedMesh
                      name="Object_45"
                      geometry={nodes.Object_45.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_45.skeleton}
                      userData={{ name: "Object_45" }}
                    />
                    <skinnedMesh
                      name="Object_46"
                      geometry={nodes.Object_46.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_46.skeleton}
                      userData={{ name: "Object_46" }}
                    />
                    <skinnedMesh
                      name="Object_47"
                      geometry={nodes.Object_47.geometry}
                      material={materials.blue}
                      skeleton={nodes.Object_47.skeleton}
                      userData={{ name: "Object_47" }}
                    />
                    <skinnedMesh
                      name="Object_48"
                      geometry={nodes.Object_48.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_48.skeleton}
                      userData={{ name: "Object_48" }}
                    />
                    <skinnedMesh
                      name="Object_49"
                      geometry={nodes.Object_49.geometry}
                      material={materials.METALSmoothAluminium}
                      skeleton={nodes.Object_49.skeleton}
                      userData={{ name: "Object_49" }}
                    />
                    <skinnedMesh
                      name="Object_51"
                      geometry={nodes.Object_51.geometry}
                      material={materials.Material_45}
                      skeleton={nodes.Object_51.skeleton}
                      userData={{ name: "Object_51" }}
                    />
                    <skinnedMesh
                      name="Object_52"
                      geometry={nodes.Object_52.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_52.skeleton}
                      userData={{ name: "Object_52" }}
                    />
                    <skinnedMesh
                      name="Object_53"
                      geometry={nodes.Object_53.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_53.skeleton}
                      userData={{ name: "Object_53" }}
                    />
                    <skinnedMesh
                      name="Object_54"
                      geometry={nodes.Object_54.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_54.skeleton}
                      userData={{ name: "Object_54" }}
                    />
                    <skinnedMesh
                      name="Object_56"
                      geometry={nodes.Object_56.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_56.skeleton}
                      userData={{ name: "Object_56" }}
                    />
                    <skinnedMesh
                      name="Object_58"
                      geometry={nodes.Object_58.geometry}
                      material={materials.Material_45}
                      skeleton={nodes.Object_58.skeleton}
                      userData={{ name: "Object_58" }}
                    />
                    <skinnedMesh
                      name="Object_59"
                      geometry={nodes.Object_59.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_59.skeleton}
                      userData={{ name: "Object_59" }}
                    />
                    <skinnedMesh
                      name="Object_60"
                      geometry={nodes.Object_60.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_60.skeleton}
                      userData={{ name: "Object_60" }}
                    />
                    <skinnedMesh
                      name="Object_61"
                      geometry={nodes.Object_61.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_61.skeleton}
                      userData={{ name: "Object_61" }}
                    />
                    <skinnedMesh
                      name="Object_63"
                      geometry={nodes.Object_63.geometry}
                      material={materials.Clean_Iron_Mash}
                      skeleton={nodes.Object_63.skeleton}
                      userData={{ name: "Object_63" }}
                    />
                    <skinnedMesh
                      name="Object_64"
                      geometry={nodes.Object_64.geometry}
                      material={materials.Clean_Iron_scrow}
                      skeleton={nodes.Object_64.skeleton}
                      userData={{ name: "Object_64" }}
                    />
                    <skinnedMesh
                      name="Object_65"
                      geometry={nodes.Object_65.geometry}
                      material={materials.standardSurface1}
                      skeleton={nodes.Object_65.skeleton}
                      userData={{ name: "Object_65" }}
                    />
                    <skinnedMesh
                      name="Object_66"
                      geometry={nodes.Object_66.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_66.skeleton}
                      userData={{ name: "Object_66" }}
                    />
                    <skinnedMesh
                      name="Object_67"
                      geometry={nodes.Object_67.geometry}
                      material={materials.Inside_camera_Black}
                      skeleton={nodes.Object_67.skeleton}
                      userData={{ name: "Object_67" }}
                    />
                    <skinnedMesh
                      name="Object_68"
                      geometry={nodes.Object_68.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_68.skeleton}
                      userData={{ name: "Object_68" }}
                    />
                    <skinnedMesh
                      name="Object_69"
                      geometry={nodes.Object_69.geometry}
                      material={materials.PMMA_Opaque_Olive}
                      skeleton={nodes.Object_69.skeleton}
                      userData={{ name: "Object_69" }}
                    />
                    <skinnedMesh
                      name="Object_70"
                      geometry={nodes.Object_70.geometry}
                      material={materials.METALSmoothAluminium}
                      skeleton={nodes.Object_70.skeleton}
                      userData={{ name: "Object_70" }}
                    />
                    <skinnedMesh
                      name="Object_71"
                      geometry={nodes.Object_71.geometry}
                      material={materials.GLASSDecorativeRainbow_Reflection}
                      skeleton={nodes.Object_71.skeleton}
                      userData={{ name: "Object_71" }}
                    />
                    <skinnedMesh
                      name="Object_72"
                      geometry={nodes.Object_72.geometry}
                      material={materials.Glass_Object_Solid_Simple}
                      skeleton={nodes.Object_72.skeleton}
                      userData={{ name: "Object_72" }}
                    />
                    <skinnedMesh
                      name="Object_73"
                      geometry={nodes.Object_73.geometry}
                      material={materials.blue}
                      skeleton={nodes.Object_73.skeleton}
                      userData={{ name: "Object_73" }}
                    />
                    <skinnedMesh
                      name="Object_74"
                      geometry={nodes.Object_74.geometry}
                      material={materials.blue_crim}
                      skeleton={nodes.Object_74.skeleton}
                      userData={{ name: "Object_74" }}
                    />
                    <skinnedMesh
                      name="Object_76"
                      geometry={nodes.Object_76.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_76.skeleton}
                      userData={{ name: "Object_76" }}
                    />
                    <skinnedMesh
                      name="Object_77"
                      geometry={nodes.Object_77.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_77.skeleton}
                      userData={{ name: "Object_77" }}
                    />
                    <skinnedMesh
                      name="Object_78"
                      geometry={nodes.Object_78.geometry}
                      material={materials.Material_45}
                      skeleton={nodes.Object_78.skeleton}
                      userData={{ name: "Object_78" }}
                    />
                    <skinnedMesh
                      name="Object_79"
                      geometry={nodes.Object_79.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_79.skeleton}
                      userData={{ name: "Object_79" }}
                    />
                    <skinnedMesh
                      name="Object_81"
                      geometry={nodes.Object_81.geometry}
                      material={materials.Clean_Iron_scrow}
                      skeleton={nodes.Object_81.skeleton}
                      userData={{ name: "Object_81" }}
                    />
                    <skinnedMesh
                      name="Object_82"
                      geometry={nodes.Object_82.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_82.skeleton}
                      userData={{ name: "Object_82" }}
                    />
                    <skinnedMesh
                      name="Object_83"
                      geometry={nodes.Object_83.geometry}
                      material={materials.blue}
                      skeleton={nodes.Object_83.skeleton}
                      userData={{ name: "Object_83" }}
                    />
                    <skinnedMesh
                      name="Object_84"
                      geometry={nodes.Object_84.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_84.skeleton}
                      userData={{ name: "Object_84" }}
                    />
                    <skinnedMesh
                      name="Object_85"
                      geometry={nodes.Object_85.geometry}
                      material={materials.Glass_Object_Solid_Simple_black}
                      skeleton={nodes.Object_85.skeleton}
                      userData={{ name: "Object_85" }}
                    />
                    <skinnedMesh
                      name="Object_86"
                      geometry={nodes.Object_86.geometry}
                      material={materials.PMMA_Opaque_Olive}
                      skeleton={nodes.Object_86.skeleton}
                      userData={{ name: "Object_86" }}
                    />
                    <skinnedMesh
                      name="Object_87"
                      geometry={nodes.Object_87.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_87.skeleton}
                      userData={{ name: "Object_87" }}
                    />
                    <skinnedMesh
                      name="Object_88"
                      geometry={nodes.Object_88.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_88.skeleton}
                      userData={{ name: "Object_88" }}
                    />
                    <skinnedMesh
                      name="Object_90"
                      geometry={nodes.Object_90.geometry}
                      material={materials.Material_45}
                      skeleton={nodes.Object_90.skeleton}
                      userData={{ name: "Object_90" }}
                    />
                    <skinnedMesh
                      name="Object_91"
                      geometry={nodes.Object_91.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_91.skeleton}
                      userData={{ name: "Object_91" }}
                    />
                    <skinnedMesh
                      name="Object_92"
                      geometry={nodes.Object_92.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_92.skeleton}
                      userData={{ name: "Object_92" }}
                    />
                    <skinnedMesh
                      name="Object_93"
                      geometry={nodes.Object_93.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_93.skeleton}
                      userData={{ name: "Object_93" }}
                    />
                    <skinnedMesh
                      name="Object_95"
                      geometry={nodes.Object_95.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_95.skeleton}
                      userData={{ name: "Object_95" }}
                    />
                    <skinnedMesh
                      name="Object_96"
                      geometry={nodes.Object_96.geometry}
                      material={materials.blue}
                      skeleton={nodes.Object_96.skeleton}
                      userData={{ name: "Object_96" }}
                    />
                    <skinnedMesh
                      name="Object_97"
                      geometry={nodes.Object_97.geometry}
                      material={materials.METALSmoothAluminium}
                      skeleton={nodes.Object_97.skeleton}
                      userData={{ name: "Object_97" }}
                    />
                    <skinnedMesh
                      name="Object_98"
                      geometry={nodes.Object_98.geometry}
                      material={materials.Glass_Object_Solid_Simple_black}
                      skeleton={nodes.Object_98.skeleton}
                      userData={{ name: "Object_98" }}
                    />
                    <skinnedMesh
                      name="Object_99"
                      geometry={nodes.Object_99.geometry}
                      material={materials.PMMA_Opaque_Olive}
                      skeleton={nodes.Object_99.skeleton}
                      userData={{ name: "Object_99" }}
                    />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials.Special_Finish_Weathered_Black_Steel}
                      skeleton={nodes.Object_100.skeleton}
                      userData={{ name: "Object_100" }}
                    />
                    <skinnedMesh
                      name="Object_101"
                      geometry={nodes.Object_101.geometry}
                      material={materials.PVC_Fb_Black}
                      skeleton={nodes.Object_101.skeleton}
                      userData={{ name: "Object_101" }}
                    />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials.Clean_Iron_scrow}
                      skeleton={nodes.Object_102.skeleton}
                      userData={{ name: "Object_102" }}
                    />
                    <skinnedMesh
                      name="Object_103"
                      geometry={nodes.Object_103.geometry}
                      material={materials.Clean_Aluminium_Matte}
                      skeleton={nodes.Object_103.skeleton}
                      userData={{ name: "Object_103" }}
                    />
                    <skinnedMesh
                      name="Object_105"
                      geometry={nodes.Object_105.geometry}
                      material={materials.METALSmoothAluminium}
                      skeleton={nodes.Object_105.skeleton}
                      userData={{ name: "Object_105" }}
                    />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials.METALSmoothChrome_Satin}
                      skeleton={nodes.Object_106.skeleton}
                      userData={{ name: "Object_106" }}
                    />
                    <skinnedMesh
                      name="Object_107"
                      geometry={nodes.Object_107.geometry}
                      material={materials.Glass_Object_Solid_Simple}
                      skeleton={nodes.Object_107.skeleton}
                      userData={{ name: "Object_107" }}
                    />
                    <skinnedMesh
                      name="Object_108"
                      geometry={nodes.Object_108.geometry}
                      material={materials.GLASSDecorativeRainbow_Reflection}
                      skeleton={nodes.Object_108.skeleton}
                      userData={{ name: "Object_108" }}
                    />
                    <skinnedMesh
                      name="Object_109"
                      geometry={nodes.Object_109.geometry}
                      material={materials.Inside_camera_Black}
                      skeleton={nodes.Object_109.skeleton}
                      userData={{ name: "Object_109" }}
                    />
                    <skinnedMesh
                      name="Object_110"
                      geometry={nodes.Object_110.geometry}
                      material={materials.Inside_out_camera_Black}
                      skeleton={nodes.Object_110.skeleton}
                      userData={{ name: "Object_110" }}
                    />
                    <group name="Object_31" userData={{ name: "Object_31" }} />
                    <group name="Object_40" userData={{ name: "Object_40" }} />
                    <group name="Object_50" userData={{ name: "Object_50" }} />
                    <group name="Object_55" userData={{ name: "Object_55" }} />
                    <group name="Object_57" userData={{ name: "Object_57" }} />
                    <group name="Object_62" userData={{ name: "Object_62" }} />
                    <group name="Object_75" userData={{ name: "Object_75" }} />
                    <group name="Object_80" userData={{ name: "Object_80" }} />
                    <group name="Object_89" userData={{ name: "Object_89" }} />
                    <group name="Object_94" userData={{ name: "Object_94" }} />
                    <group
                      name="Object_104"
                      userData={{ name: "Object_104" }}
                    />
                  </group>
                </group>
                <group
                  name="LeftBack_Handle"
                  userData={{ name: "LeftBack_Handle" }}
                />
                <group
                  name="LeftFront_Handle"
                  userData={{ name: "LeftFront_Handle" }}
                />
                <group
                  name="RightFront_Wing"
                  userData={{ name: "RightFront_Wing" }}
                />
                <group
                  name="Camera_Holder"
                  userData={{ name: "Camera_Holder" }}
                />
                <group
                  name="LeftFront_Wing"
                  userData={{ name: "LeftFront_Wing" }}
                />
                <group name="DroneBody" userData={{ name: "DroneBody" }} />
                <group
                  name="LeftBack_Wing"
                  userData={{ name: "LeftBack_Wing" }}
                />
                <group
                  name="RightBack_Handle"
                  userData={{ name: "RightBack_Handle" }}
                />
                <group
                  name="RightBack_Wing"
                  userData={{ name: "RightBack_Wing" }}
                />
                <group
                  name="RightFront_Handle"
                  userData={{ name: "RightFront_Handle" }}
                />
                <group name="Camera" userData={{ name: "Camera" }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/drone_animv1.glb");

export { DroneModel };
